# Generated by Django 5.2.4 on 2025-07-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author")},
        ),
    ]
